---
# tasks file for nodejs

- name: apt update
  apt:
      update_cache: yes
- name: install node and npm
  apt: "name={{ item }} state=present"
  with_items:
    - nodejs
    - npm
    - nodejs-legacy