---
# tasks file for jenkins
- name: command set
  command: sudo wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
  command: sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: apt update
  apt:
      update_cache: yes

#- name: Install javajdk
#  command: sudo apt install -y openjdk-8-jdk

#- name: Install Jenkins
#  command: sudo apt install -y jenkins --allow-unauthenticated

- name: Install Java using Ansible
  become: yes
  apt:
        name: "{{ packages }}"
        state: present
  vars:
        packages:
           - openjdk-8-jdk


#- name:  Install Jenkins & java sdk
#  apt: "name={{ item }} state=present"
#  with_items:
#    - openjdk-8-jdk
#    - jenkins --allow-unauthenticated

- name: Start Jenkins 
  service: 
    name: jenkins 
    enabled: yes 
    state: started 
