---
# tasks file for jenkins
- name: command set
  command: sudo wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
  command: sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: apt update
  apt:
      update_cache: yes

- name:  Install Jenkins & java sdk
  apt: "name={{ item }} state=present"
  with_items:
    - openjdk-8-jdk
    - jenkins

- name: Start Jenkins 
  service: 
    name: jenkins 
    enabled: yes 
    state: started 
